on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    
    steps:
    
    - name: Hello world action step
      id: hello
      uses: actions/hello-world-docker-action@v3
      with:
        who-to-greet: 'Name to Test'
    
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
    
    - name: download log data
      uses: actions/upload-artifact@v1
      with:
        name: logs
        path: test.log  
