on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    
    steps:
    
    - name: Hello world action step
      id: hello
      run: docker run danstan5/seedlink-metadata-scripts
    
    - name: State finished
      run: echo "This is finished"
